// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ChannelSwitchEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ChannelSwitchEvent {
        __init(_i, _bb)
        return this
    }
    val fromChannel : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val fromChannelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun fromChannelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val toChannel : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field toChannel")
            }
        }
    val toChannelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun toChannelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val recipient : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val recipientAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun recipientInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsChannelSwitchEvent(_bb: ByteBuffer): ChannelSwitchEvent = getRootAsChannelSwitchEvent(_bb, ChannelSwitchEvent())
        fun getRootAsChannelSwitchEvent(_bb: ByteBuffer, obj: ChannelSwitchEvent): ChannelSwitchEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createChannelSwitchEvent(builder: FlatBufferBuilder, fromChannelOffset: Int, toChannelOffset: Int, recipientOffset: Int) : Int {
            builder.startTable(3)
            addRecipient(builder, recipientOffset)
            addToChannel(builder, toChannelOffset)
            addFromChannel(builder, fromChannelOffset)
            return endChannelSwitchEvent(builder)
        }
        fun startChannelSwitchEvent(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addFromChannel(builder: FlatBufferBuilder, fromChannel: Int) = builder.addOffset(0, fromChannel, 0)
        fun addToChannel(builder: FlatBufferBuilder, toChannel: Int) = builder.addOffset(1, toChannel, 0)
        fun addRecipient(builder: FlatBufferBuilder, recipient: Int) = builder.addOffset(2, recipient, 0)
        fun endChannelSwitchEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 6)
            return o
        }
    }
}
