// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ContentDeltaEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ContentDeltaEvent {
        __init(_i, _bb)
        return this
    }
    val text : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field text")
            }
        }
    val textAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun textInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val channel : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val channelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun channelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val tokenIndex : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun mutateTokenIndex(tokenIndex: UInt) : Boolean {
        val o = __offset(8)
        return if (o != 0) {
            bb.putInt(o + bb_pos, tokenIndex.toInt())
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsContentDeltaEvent(_bb: ByteBuffer): ContentDeltaEvent = getRootAsContentDeltaEvent(_bb, ContentDeltaEvent())
        fun getRootAsContentDeltaEvent(_bb: ByteBuffer, obj: ContentDeltaEvent): ContentDeltaEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createContentDeltaEvent(builder: FlatBufferBuilder, textOffset: Int, channelOffset: Int, tokenIndex: UInt) : Int {
            builder.startTable(3)
            addTokenIndex(builder, tokenIndex)
            addChannel(builder, channelOffset)
            addText(builder, textOffset)
            return endContentDeltaEvent(builder)
        }
        fun startContentDeltaEvent(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addText(builder: FlatBufferBuilder, text: Int) = builder.addOffset(0, text, 0)
        fun addChannel(builder: FlatBufferBuilder, channel: Int) = builder.addOffset(1, channel, 0)
        fun addTokenIndex(builder: FlatBufferBuilder, tokenIndex: UInt) = builder.addInt(2, tokenIndex.toInt(), 0)
        fun endContentDeltaEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
