// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

@Suppress("unused")
class EventType private constructor() {
    companion object {
        const val ToolCall: Byte = 0
        const val ChannelSwitch: Byte = 1
        const val ContentDelta: Byte = 2
        const val MessageComplete: Byte = 3
        const val StreamComplete: Byte = 4
        const val ParseError: Byte = 5
    }
}
