// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

@Suppress("unused")
class EventData private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val ToolCallEvent: UByte = 1u
        const val ChannelSwitchEvent: UByte = 2u
        const val ContentDeltaEvent: UByte = 3u
        const val MessageCompleteEvent: UByte = 4u
        const val StreamCompleteEvent: UByte = 5u
        const val ParseErrorEvent: UByte = 6u
    }
}
