// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class MessageCompleteEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : MessageCompleteEvent {
        __init(_i, _bb)
        return this
    }
    val role : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field role")
            }
        }
    val roleAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun roleInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val channel : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val channelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun channelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val totalContentLength : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun mutateTotalContentLength(totalContentLength: UInt) : Boolean {
        val o = __offset(8)
        return if (o != 0) {
            bb.putInt(o + bb_pos, totalContentLength.toInt())
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMessageCompleteEvent(_bb: ByteBuffer): MessageCompleteEvent = getRootAsMessageCompleteEvent(_bb, MessageCompleteEvent())
        fun getRootAsMessageCompleteEvent(_bb: ByteBuffer, obj: MessageCompleteEvent): MessageCompleteEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMessageCompleteEvent(builder: FlatBufferBuilder, roleOffset: Int, channelOffset: Int, totalContentLength: UInt) : Int {
            builder.startTable(3)
            addTotalContentLength(builder, totalContentLength)
            addChannel(builder, channelOffset)
            addRole(builder, roleOffset)
            return endMessageCompleteEvent(builder)
        }
        fun startMessageCompleteEvent(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addRole(builder: FlatBufferBuilder, role: Int) = builder.addOffset(0, role, 0)
        fun addChannel(builder: FlatBufferBuilder, channel: Int) = builder.addOffset(1, channel, 0)
        fun addTotalContentLength(builder: FlatBufferBuilder, totalContentLength: UInt) = builder.addInt(2, totalContentLength.toInt(), 0)
        fun endMessageCompleteEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
