// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class NoesisEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : NoesisEvent {
        __init(_i, _bb)
        return this
    }
    val type : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun mutateType(type: Byte) : Boolean {
        val o = __offset(4)
        return if (o != 0) {
            bb.put(o + bb_pos, type)
            true
        } else {
            false
        }
    }
    val dataType : UByte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun mutateDataType(dataType: UByte) : Boolean {
        val o = __offset(6)
        return if (o != 0) {
            bb.put(o + bb_pos, dataType.toByte())
            true
        } else {
            false
        }
    }
    fun data(obj: Table) : Table? {
        val o = __offset(8); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    val timestampNs : ULong
        get() {
            val o = __offset(10)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    fun mutateTimestampNs(timestampNs: ULong) : Boolean {
        val o = __offset(10)
        return if (o != 0) {
            bb.putLong(o + bb_pos, timestampNs.toLong())
            true
        } else {
            false
        }
    }
    val sequenceId : UInt
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun mutateSequenceId(sequenceId: UInt) : Boolean {
        val o = __offset(12)
        return if (o != 0) {
            bb.putInt(o + bb_pos, sequenceId.toInt())
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsNoesisEvent(_bb: ByteBuffer): NoesisEvent = getRootAsNoesisEvent(_bb, NoesisEvent())
        fun getRootAsNoesisEvent(_bb: ByteBuffer, obj: NoesisEvent): NoesisEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createNoesisEvent(builder: FlatBufferBuilder, type: Byte, dataType: UByte, dataOffset: Int, timestampNs: ULong, sequenceId: UInt) : Int {
            builder.startTable(5)
            addTimestampNs(builder, timestampNs)
            addSequenceId(builder, sequenceId)
            addData(builder, dataOffset)
            addDataType(builder, dataType)
            addType(builder, type)
            return endNoesisEvent(builder)
        }
        fun startNoesisEvent(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addType(builder: FlatBufferBuilder, type: Byte) = builder.addByte(0, type, 0)
        fun addDataType(builder: FlatBufferBuilder, dataType: UByte) = builder.addByte(1, dataType.toByte(), 0)
        fun addData(builder: FlatBufferBuilder, data: Int) = builder.addOffset(2, data, 0)
        fun addTimestampNs(builder: FlatBufferBuilder, timestampNs: ULong) = builder.addLong(3, timestampNs.toLong(), 0)
        fun addSequenceId(builder: FlatBufferBuilder, sequenceId: UInt) = builder.addInt(4, sequenceId.toInt(), 0)
        fun endNoesisEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 8)
            return o
        }
        fun finishNoesisEventBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedNoesisEventBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
