// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ParseErrorEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ParseErrorEvent {
        __init(_i, _bb)
        return this
    }
    val errorMessage : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field errorMessage")
            }
        }
    val errorMessageAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun errorMessageInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val tokenPosition : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun mutateTokenPosition(tokenPosition: UInt) : Boolean {
        val o = __offset(6)
        return if (o != 0) {
            bb.putInt(o + bb_pos, tokenPosition.toInt())
            true
        } else {
            false
        }
    }
    val recoveryAttempted : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun mutateRecoveryAttempted(recoveryAttempted: Boolean) : Boolean {
        val o = __offset(8)
        return if (o != 0) {
            bb.put(o + bb_pos, (if(recoveryAttempted) 1 else 0).toByte())
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsParseErrorEvent(_bb: ByteBuffer): ParseErrorEvent = getRootAsParseErrorEvent(_bb, ParseErrorEvent())
        fun getRootAsParseErrorEvent(_bb: ByteBuffer, obj: ParseErrorEvent): ParseErrorEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createParseErrorEvent(builder: FlatBufferBuilder, errorMessageOffset: Int, tokenPosition: UInt, recoveryAttempted: Boolean) : Int {
            builder.startTable(3)
            addTokenPosition(builder, tokenPosition)
            addErrorMessage(builder, errorMessageOffset)
            addRecoveryAttempted(builder, recoveryAttempted)
            return endParseErrorEvent(builder)
        }
        fun startParseErrorEvent(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addErrorMessage(builder: FlatBufferBuilder, errorMessage: Int) = builder.addOffset(0, errorMessage, 0)
        fun addTokenPosition(builder: FlatBufferBuilder, tokenPosition: UInt) = builder.addInt(1, tokenPosition.toInt(), 0)
        fun addRecoveryAttempted(builder: FlatBufferBuilder, recoveryAttempted: Boolean) = builder.addBoolean(2, recoveryAttempted, false)
        fun endParseErrorEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
