// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class StreamCompleteEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StreamCompleteEvent {
        __init(_i, _bb)
        return this
    }
    val reason : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field reason")
            }
        }
    val reasonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun reasonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val totalTokens : UInt
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun mutateTotalTokens(totalTokens: UInt) : Boolean {
        val o = __offset(6)
        return if (o != 0) {
            bb.putInt(o + bb_pos, totalTokens.toInt())
            true
        } else {
            false
        }
    }
    val generationTimeMs : UInt
        get() {
            val o = __offset(8)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    fun mutateGenerationTimeMs(generationTimeMs: UInt) : Boolean {
        val o = __offset(8)
        return if (o != 0) {
            bb.putInt(o + bb_pos, generationTimeMs.toInt())
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsStreamCompleteEvent(_bb: ByteBuffer): StreamCompleteEvent = getRootAsStreamCompleteEvent(_bb, StreamCompleteEvent())
        fun getRootAsStreamCompleteEvent(_bb: ByteBuffer, obj: StreamCompleteEvent): StreamCompleteEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStreamCompleteEvent(builder: FlatBufferBuilder, reasonOffset: Int, totalTokens: UInt, generationTimeMs: UInt) : Int {
            builder.startTable(3)
            addGenerationTimeMs(builder, generationTimeMs)
            addTotalTokens(builder, totalTokens)
            addReason(builder, reasonOffset)
            return endStreamCompleteEvent(builder)
        }
        fun startStreamCompleteEvent(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addReason(builder: FlatBufferBuilder, reason: Int) = builder.addOffset(0, reason, 0)
        fun addTotalTokens(builder: FlatBufferBuilder, totalTokens: UInt) = builder.addInt(1, totalTokens.toInt(), 0)
        fun addGenerationTimeMs(builder: FlatBufferBuilder, generationTimeMs: UInt) = builder.addInt(2, generationTimeMs.toInt(), 0)
        fun endStreamCompleteEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
