// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.events

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class ToolCallEvent : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : ToolCallEvent {
        __init(_i, _bb)
        return this
    }
    val toolName : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field toolName")
            }
        }
    val toolNameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun toolNameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val argumentsJson : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field argumentsJson")
            }
        }
    val argumentsJsonAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun argumentsJsonInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val recipient : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val recipientAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun recipientInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val channel : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val channelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun channelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsToolCallEvent(_bb: ByteBuffer): ToolCallEvent = getRootAsToolCallEvent(_bb, ToolCallEvent())
        fun getRootAsToolCallEvent(_bb: ByteBuffer, obj: ToolCallEvent): ToolCallEvent {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createToolCallEvent(builder: FlatBufferBuilder, toolNameOffset: Int, argumentsJsonOffset: Int, recipientOffset: Int, channelOffset: Int) : Int {
            builder.startTable(4)
            addChannel(builder, channelOffset)
            addRecipient(builder, recipientOffset)
            addArgumentsJson(builder, argumentsJsonOffset)
            addToolName(builder, toolNameOffset)
            return endToolCallEvent(builder)
        }
        fun startToolCallEvent(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addToolName(builder: FlatBufferBuilder, toolName: Int) = builder.addOffset(0, toolName, 0)
        fun addArgumentsJson(builder: FlatBufferBuilder, argumentsJson: Int) = builder.addOffset(1, argumentsJson, 0)
        fun addRecipient(builder: FlatBufferBuilder, recipient: Int) = builder.addOffset(2, recipient, 0)
        fun addChannel(builder: FlatBufferBuilder, channel: Int) = builder.addOffset(3, channel, 0)
        fun endToolCallEvent(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
                builder.required(o, 6)
            return o
        }
    }
}
