// automatically generated by the FlatBuffers compiler, do not modify

package ai.koog.noesis.protocol

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Role private constructor() {
    companion object {
        const val User: Byte = 0
        const val Assistant: Byte = 1
        const val System: Byte = 2
        const val Developer: Byte = 3
        const val Tool: Byte = 4
    }
}
@Suppress("unused")
class ReasoningEffort private constructor() {
    companion object {
        const val Low: Byte = 0
        const val Medium: Byte = 1
        const val High: Byte = 2
    }
}
@Suppress("unused")
class Message : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Message {
        __init(_i, _bb)
        return this
    }
    val role : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val content : String
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field content")
            }
        }
    val contentAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun contentInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val channel : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val channelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun channelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val recipient : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val recipientAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun recipientInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsMessage(_bb: ByteBuffer): Message = getRootAsMessage(_bb, Message())
        fun getRootAsMessage(_bb: ByteBuffer, obj: Message): Message {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createMessage(builder: FlatBufferBuilder, role: Byte, contentOffset: Int, channelOffset: Int, recipientOffset: Int) : Int {
            builder.startTable(4)
            addRecipient(builder, recipientOffset)
            addChannel(builder, channelOffset)
            addContent(builder, contentOffset)
            addRole(builder, role)
            return endMessage(builder)
        }
        fun startMessage(builder: FlatBufferBuilder) = builder.startTable(4)
        fun addRole(builder: FlatBufferBuilder, role: Byte) = builder.addByte(0, role, 0)
        fun addContent(builder: FlatBufferBuilder, content: Int) = builder.addOffset(1, content, 0)
        fun addChannel(builder: FlatBufferBuilder, channel: Int) = builder.addOffset(2, channel, 0)
        fun addRecipient(builder: FlatBufferBuilder, recipient: Int) = builder.addOffset(3, recipient, 0)
        fun endMessage(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 6)
            return o
        }
    }
}
@Suppress("unused")
class SystemConfig : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : SystemConfig {
        __init(_i, _bb)
        return this
    }
    val modelIdentity : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val modelIdentityAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun modelIdentityInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val reasoningEffort : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 1
        }
    val knowledgeCutoff : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val knowledgeCutoffAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun knowledgeCutoffInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    val conversationStartDate : String?
        get() {
            val o = __offset(10)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val conversationStartDateAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(10, 1)
    fun conversationStartDateInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 10, 1)
    fun requiredChannels(j: Int) : String? {
        val o = __offset(12)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val requiredChannelsLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsSystemConfig(_bb: ByteBuffer): SystemConfig = getRootAsSystemConfig(_bb, SystemConfig())
        fun getRootAsSystemConfig(_bb: ByteBuffer, obj: SystemConfig): SystemConfig {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createSystemConfig(builder: FlatBufferBuilder, modelIdentityOffset: Int, reasoningEffort: Byte, knowledgeCutoffOffset: Int, conversationStartDateOffset: Int, requiredChannelsOffset: Int) : Int {
            builder.startTable(5)
            addRequiredChannels(builder, requiredChannelsOffset)
            addConversationStartDate(builder, conversationStartDateOffset)
            addKnowledgeCutoff(builder, knowledgeCutoffOffset)
            addModelIdentity(builder, modelIdentityOffset)
            addReasoningEffort(builder, reasoningEffort)
            return endSystemConfig(builder)
        }
        fun startSystemConfig(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addModelIdentity(builder: FlatBufferBuilder, modelIdentity: Int) = builder.addOffset(0, modelIdentity, 0)
        fun addReasoningEffort(builder: FlatBufferBuilder, reasoningEffort: Byte) = builder.addByte(1, reasoningEffort, 1)
        fun addKnowledgeCutoff(builder: FlatBufferBuilder, knowledgeCutoff: Int) = builder.addOffset(2, knowledgeCutoff, 0)
        fun addConversationStartDate(builder: FlatBufferBuilder, conversationStartDate: Int) = builder.addOffset(3, conversationStartDate, 0)
        fun addRequiredChannels(builder: FlatBufferBuilder, requiredChannels: Int) = builder.addOffset(4, requiredChannels, 0)
        fun createRequiredChannelsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startRequiredChannelsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endSystemConfig(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
@Suppress("unused")
class DeveloperConfig : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : DeveloperConfig {
        __init(_i, _bb)
        return this
    }
    val instructions : String
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                throw AssertionError("No value for (required) field instructions")
            }
        }
    val instructionsAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun instructionsInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsDeveloperConfig(_bb: ByteBuffer): DeveloperConfig = getRootAsDeveloperConfig(_bb, DeveloperConfig())
        fun getRootAsDeveloperConfig(_bb: ByteBuffer, obj: DeveloperConfig): DeveloperConfig {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createDeveloperConfig(builder: FlatBufferBuilder, instructionsOffset: Int) : Int {
            builder.startTable(1)
            addInstructions(builder, instructionsOffset)
            return endDeveloperConfig(builder)
        }
        fun startDeveloperConfig(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addInstructions(builder: FlatBufferBuilder, instructions: Int) = builder.addOffset(0, instructions, 0)
        fun endDeveloperConfig(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 4)
            return o
        }
    }
}
@Suppress("unused")
class GenerationRequest : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : GenerationRequest {
        __init(_i, _bb)
        return this
    }
    val modelHandle : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    val systemConfig : ai.koog.noesis.protocol.SystemConfig? get() = systemConfig(ai.koog.noesis.protocol.SystemConfig())
    fun systemConfig(obj: ai.koog.noesis.protocol.SystemConfig) : ai.koog.noesis.protocol.SystemConfig? {
        val o = __offset(6)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    val developerConfig : ai.koog.noesis.protocol.DeveloperConfig? get() = developerConfig(ai.koog.noesis.protocol.DeveloperConfig())
    fun developerConfig(obj: ai.koog.noesis.protocol.DeveloperConfig) : ai.koog.noesis.protocol.DeveloperConfig? {
        val o = __offset(8)
        return if (o != 0) {
            obj.__assign(__indirect(o + bb_pos), bb)
        } else {
            null
        }
    }
    fun messages(j: Int) : ai.koog.noesis.protocol.Message = messages(ai.koog.noesis.protocol.Message(), j)
    fun messages(obj: ai.koog.noesis.protocol.Message, j: Int) : ai.koog.noesis.protocol.Message {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            throw IndexOutOfBoundsException("Index out of range: $j, vector messages is empty")
        }
    }
    val messagesLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val maxTokens : Int
        get() {
            val o = __offset(12)
            return if(o != 0) bb.getInt(o + bb_pos) else 2048
        }
    val temperature : Float
        get() {
            val o = __offset(14)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.7f
        }
    val topP : Float
        get() {
            val o = __offset(16)
            return if(o != 0) bb.getFloat(o + bb_pos) else 0.9f
        }
    val topK : Int
        get() {
            val o = __offset(18)
            return if(o != 0) bb.getInt(o + bb_pos) else 40
        }
    val seed : UInt
        get() {
            val o = __offset(20)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 42u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsGenerationRequest(_bb: ByteBuffer): GenerationRequest = getRootAsGenerationRequest(_bb, GenerationRequest())
        fun getRootAsGenerationRequest(_bb: ByteBuffer, obj: GenerationRequest): GenerationRequest {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createGenerationRequest(builder: FlatBufferBuilder, modelHandle: Long, systemConfigOffset: Int, developerConfigOffset: Int, messagesOffset: Int, maxTokens: Int, temperature: Float, topP: Float, topK: Int, seed: UInt) : Int {
            builder.startTable(9)
            addModelHandle(builder, modelHandle)
            addSeed(builder, seed)
            addTopK(builder, topK)
            addTopP(builder, topP)
            addTemperature(builder, temperature)
            addMaxTokens(builder, maxTokens)
            addMessages(builder, messagesOffset)
            addDeveloperConfig(builder, developerConfigOffset)
            addSystemConfig(builder, systemConfigOffset)
            return endGenerationRequest(builder)
        }
        fun startGenerationRequest(builder: FlatBufferBuilder) = builder.startTable(9)
        fun addModelHandle(builder: FlatBufferBuilder, modelHandle: Long) = builder.addLong(0, modelHandle, 0L)
        fun addSystemConfig(builder: FlatBufferBuilder, systemConfig: Int) = builder.addOffset(1, systemConfig, 0)
        fun addDeveloperConfig(builder: FlatBufferBuilder, developerConfig: Int) = builder.addOffset(2, developerConfig, 0)
        fun addMessages(builder: FlatBufferBuilder, messages: Int) = builder.addOffset(3, messages, 0)
        fun createMessagesVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startMessagesVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addMaxTokens(builder: FlatBufferBuilder, maxTokens: Int) = builder.addInt(4, maxTokens, 2048)
        fun addTemperature(builder: FlatBufferBuilder, temperature: Float) = builder.addFloat(5, temperature, 0.7)
        fun addTopP(builder: FlatBufferBuilder, topP: Float) = builder.addFloat(6, topP, 0.9)
        fun addTopK(builder: FlatBufferBuilder, topK: Int) = builder.addInt(7, topK, 40)
        fun addSeed(builder: FlatBufferBuilder, seed: UInt) = builder.addInt(8, seed.toInt(), 42)
        fun endGenerationRequest(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
                builder.required(o, 10)
            return o
        }
        fun finishGenerationRequestBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedGenerationRequestBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
@Suppress("unused")
class TokenChunk : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : TokenChunk {
        __init(_i, _bb)
        return this
    }
    fun tokens(j: Int) : UInt {
        val o = __offset(4)
        return if (o != 0) {
            bb.getInt(__vector(o) + j * 4).toUInt()
        } else {
            0u
        }
    }
    val tokensLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    val tokensAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 4)
    fun tokensInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 4)
    val channel : String?
        get() {
            val o = __offset(6)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val channelAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 1)
    fun channelInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 1)
    val isFinal : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsTokenChunk(_bb: ByteBuffer): TokenChunk = getRootAsTokenChunk(_bb, TokenChunk())
        fun getRootAsTokenChunk(_bb: ByteBuffer, obj: TokenChunk): TokenChunk {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createTokenChunk(builder: FlatBufferBuilder, tokensOffset: Int, channelOffset: Int, isFinal: Boolean) : Int {
            builder.startTable(3)
            addChannel(builder, channelOffset)
            addTokens(builder, tokensOffset)
            addIsFinal(builder, isFinal)
            return endTokenChunk(builder)
        }
        fun startTokenChunk(builder: FlatBufferBuilder) = builder.startTable(3)
        fun addTokens(builder: FlatBufferBuilder, tokens: Int) = builder.addOffset(0, tokens, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createTokensVector(builder: FlatBufferBuilder, data: UIntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addInt(data[i].toInt())
            }
            return builder.endVector()
        }
        fun startTokensVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addChannel(builder: FlatBufferBuilder, channel: Int) = builder.addOffset(1, channel, 0)
        fun addIsFinal(builder: FlatBufferBuilder, isFinal: Boolean) = builder.addBoolean(2, isFinal, false)
        fun endTokenChunk(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
@Suppress("unused")
class GenerationResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : GenerationResponse {
        __init(_i, _bb)
        return this
    }
    val requestId : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val requestIdAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun requestIdInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    fun tokens(j: Int) : UInt {
        val o = __offset(6)
        return if (o != 0) {
            bb.getInt(__vector(o) + j * 4).toUInt()
        } else {
            0u
        }
    }
    val tokensLength : Int
        get() {
            val o = __offset(6); return if (o != 0) __vector_len(o) else 0
        }
    val tokensAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(6, 4)
    fun tokensInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 6, 4)
    val text : String?
        get() {
            val o = __offset(8)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val textAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(8, 1)
    fun textInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 8, 1)
    fun channels(j: Int) : String? {
        val o = __offset(10)
        return if (o != 0) {
            __string(__vector(o) + j * 4)
        } else {
            null
        }
    }
    val channelsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    val metadata : String?
        get() {
            val o = __offset(12)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val metadataAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(12, 1)
    fun metadataInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 12, 1)
    val error : String?
        get() {
            val o = __offset(14)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val errorAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(14, 1)
    fun errorInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 14, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_2_10()
        fun getRootAsGenerationResponse(_bb: ByteBuffer): GenerationResponse = getRootAsGenerationResponse(_bb, GenerationResponse())
        fun getRootAsGenerationResponse(_bb: ByteBuffer, obj: GenerationResponse): GenerationResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createGenerationResponse(builder: FlatBufferBuilder, requestIdOffset: Int, tokensOffset: Int, textOffset: Int, channelsOffset: Int, metadataOffset: Int, errorOffset: Int) : Int {
            builder.startTable(6)
            addError(builder, errorOffset)
            addMetadata(builder, metadataOffset)
            addChannels(builder, channelsOffset)
            addText(builder, textOffset)
            addTokens(builder, tokensOffset)
            addRequestId(builder, requestIdOffset)
            return endGenerationResponse(builder)
        }
        fun startGenerationResponse(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addRequestId(builder: FlatBufferBuilder, requestId: Int) = builder.addOffset(0, requestId, 0)
        fun addTokens(builder: FlatBufferBuilder, tokens: Int) = builder.addOffset(1, tokens, 0)
        @kotlin.ExperimentalUnsignedTypes
        fun createTokensVector(builder: FlatBufferBuilder, data: UIntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addInt(data[i].toInt())
            }
            return builder.endVector()
        }
        fun startTokensVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addText(builder: FlatBufferBuilder, text: Int) = builder.addOffset(2, text, 0)
        fun addChannels(builder: FlatBufferBuilder, channels: Int) = builder.addOffset(3, channels, 0)
        fun createChannelsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startChannelsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addMetadata(builder: FlatBufferBuilder, metadata: Int) = builder.addOffset(4, metadata, 0)
        fun addError(builder: FlatBufferBuilder, error: Int) = builder.addOffset(5, error, 0)
        fun endGenerationResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
