// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod ai {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod koog {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod noesis {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod events {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_EVENT_TYPE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_EVENT_TYPE: i8 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_EVENT_TYPE: [EventType; 6] = [
  EventType::ToolCall,
  EventType::ChannelSwitch,
  EventType::ContentDelta,
  EventType::MessageComplete,
  EventType::StreamComplete,
  EventType::ParseError,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct EventType(pub i8);
#[allow(non_upper_case_globals)]
impl EventType {
  pub const ToolCall: Self = Self(0);
  pub const ChannelSwitch: Self = Self(1);
  pub const ContentDelta: Self = Self(2);
  pub const MessageComplete: Self = Self(3);
  pub const StreamComplete: Self = Self(4);
  pub const ParseError: Self = Self(5);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::ToolCall,
    Self::ChannelSwitch,
    Self::ContentDelta,
    Self::MessageComplete,
    Self::StreamComplete,
    Self::ParseError,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::ToolCall => Some("ToolCall"),
      Self::ChannelSwitch => Some("ChannelSwitch"),
      Self::ContentDelta => Some("ContentDelta"),
      Self::MessageComplete => Some("MessageComplete"),
      Self::StreamComplete => Some("StreamComplete"),
      Self::ParseError => Some("ParseError"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for EventType {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for EventType {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<i8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for EventType {
    type Output = EventType;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<i8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for EventType {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for EventType {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for EventType {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_EVENT_DATA: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_EVENT_DATA: u8 = 6;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_EVENT_DATA: [EventData; 7] = [
  EventData::NONE,
  EventData::ToolCallEvent,
  EventData::ChannelSwitchEvent,
  EventData::ContentDeltaEvent,
  EventData::MessageCompleteEvent,
  EventData::StreamCompleteEvent,
  EventData::ParseErrorEvent,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct EventData(pub u8);
#[allow(non_upper_case_globals)]
impl EventData {
  pub const NONE: Self = Self(0);
  pub const ToolCallEvent: Self = Self(1);
  pub const ChannelSwitchEvent: Self = Self(2);
  pub const ContentDeltaEvent: Self = Self(3);
  pub const MessageCompleteEvent: Self = Self(4);
  pub const StreamCompleteEvent: Self = Self(5);
  pub const ParseErrorEvent: Self = Self(6);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 6;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::ToolCallEvent,
    Self::ChannelSwitchEvent,
    Self::ContentDeltaEvent,
    Self::MessageCompleteEvent,
    Self::StreamCompleteEvent,
    Self::ParseErrorEvent,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::ToolCallEvent => Some("ToolCallEvent"),
      Self::ChannelSwitchEvent => Some("ChannelSwitchEvent"),
      Self::ContentDeltaEvent => Some("ContentDeltaEvent"),
      Self::MessageCompleteEvent => Some("MessageCompleteEvent"),
      Self::StreamCompleteEvent => Some("StreamCompleteEvent"),
      Self::ParseErrorEvent => Some("ParseErrorEvent"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for EventData {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for EventData {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = flatbuffers::read_scalar_at::<u8>(buf, loc);
    Self(b)
  }
}

impl flatbuffers::Push for EventData {
    type Output = EventData;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        flatbuffers::emplace_scalar::<u8>(dst, self.0);
    }
}

impl flatbuffers::EndianScalar for EventData {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for EventData {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    u8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for EventData {}
pub struct EventDataUnionTableOffset {}

pub enum ToolCallEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ToolCallEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ToolCallEvent<'a> {
  type Inner = ToolCallEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ToolCallEvent<'a> {
  pub const VT_TOOL_NAME: flatbuffers::VOffsetT = 4;
  pub const VT_ARGUMENTS_JSON: flatbuffers::VOffsetT = 6;
  pub const VT_RECIPIENT: flatbuffers::VOffsetT = 8;
  pub const VT_CHANNEL: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ToolCallEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ToolCallEventArgs<'args>
  ) -> flatbuffers::WIPOffset<ToolCallEvent<'bldr>> {
    let mut builder = ToolCallEventBuilder::new(_fbb);
    if let Some(x) = args.channel { builder.add_channel(x); }
    if let Some(x) = args.recipient { builder.add_recipient(x); }
    if let Some(x) = args.arguments_json { builder.add_arguments_json(x); }
    if let Some(x) = args.tool_name { builder.add_tool_name(x); }
    builder.finish()
  }


  #[inline]
  pub fn tool_name(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ToolCallEvent::VT_TOOL_NAME, None).unwrap()}
  }
  #[inline]
  pub fn arguments_json(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ToolCallEvent::VT_ARGUMENTS_JSON, None).unwrap()}
  }
  #[inline]
  pub fn recipient(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ToolCallEvent::VT_RECIPIENT, None)}
  }
  #[inline]
  pub fn channel(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ToolCallEvent::VT_CHANNEL, None)}
  }
}

impl flatbuffers::Verifiable for ToolCallEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("tool_name", Self::VT_TOOL_NAME, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("arguments_json", Self::VT_ARGUMENTS_JSON, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("recipient", Self::VT_RECIPIENT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("channel", Self::VT_CHANNEL, false)?
     .finish();
    Ok(())
  }
}
pub struct ToolCallEventArgs<'a> {
    pub tool_name: Option<flatbuffers::WIPOffset<&'a str>>,
    pub arguments_json: Option<flatbuffers::WIPOffset<&'a str>>,
    pub recipient: Option<flatbuffers::WIPOffset<&'a str>>,
    pub channel: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ToolCallEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    ToolCallEventArgs {
      tool_name: None, // required field
      arguments_json: None, // required field
      recipient: None,
      channel: None,
    }
  }
}

pub struct ToolCallEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ToolCallEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_tool_name(&mut self, tool_name: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ToolCallEvent::VT_TOOL_NAME, tool_name);
  }
  #[inline]
  pub fn add_arguments_json(&mut self, arguments_json: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ToolCallEvent::VT_ARGUMENTS_JSON, arguments_json);
  }
  #[inline]
  pub fn add_recipient(&mut self, recipient: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ToolCallEvent::VT_RECIPIENT, recipient);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ToolCallEvent::VT_CHANNEL, channel);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ToolCallEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ToolCallEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ToolCallEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ToolCallEvent::VT_TOOL_NAME,"tool_name");
    self.fbb_.required(o, ToolCallEvent::VT_ARGUMENTS_JSON,"arguments_json");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ToolCallEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ToolCallEvent");
      ds.field("tool_name", &self.tool_name());
      ds.field("arguments_json", &self.arguments_json());
      ds.field("recipient", &self.recipient());
      ds.field("channel", &self.channel());
      ds.finish()
  }
}
pub enum ChannelSwitchEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ChannelSwitchEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ChannelSwitchEvent<'a> {
  type Inner = ChannelSwitchEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ChannelSwitchEvent<'a> {
  pub const VT_FROM_CHANNEL: flatbuffers::VOffsetT = 4;
  pub const VT_TO_CHANNEL: flatbuffers::VOffsetT = 6;
  pub const VT_RECIPIENT: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ChannelSwitchEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ChannelSwitchEventArgs<'args>
  ) -> flatbuffers::WIPOffset<ChannelSwitchEvent<'bldr>> {
    let mut builder = ChannelSwitchEventBuilder::new(_fbb);
    if let Some(x) = args.recipient { builder.add_recipient(x); }
    if let Some(x) = args.to_channel { builder.add_to_channel(x); }
    if let Some(x) = args.from_channel { builder.add_from_channel(x); }
    builder.finish()
  }


  #[inline]
  pub fn from_channel(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ChannelSwitchEvent::VT_FROM_CHANNEL, None)}
  }
  #[inline]
  pub fn to_channel(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ChannelSwitchEvent::VT_TO_CHANNEL, None).unwrap()}
  }
  #[inline]
  pub fn recipient(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ChannelSwitchEvent::VT_RECIPIENT, None)}
  }
}

impl flatbuffers::Verifiable for ChannelSwitchEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("from_channel", Self::VT_FROM_CHANNEL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("to_channel", Self::VT_TO_CHANNEL, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("recipient", Self::VT_RECIPIENT, false)?
     .finish();
    Ok(())
  }
}
pub struct ChannelSwitchEventArgs<'a> {
    pub from_channel: Option<flatbuffers::WIPOffset<&'a str>>,
    pub to_channel: Option<flatbuffers::WIPOffset<&'a str>>,
    pub recipient: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ChannelSwitchEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    ChannelSwitchEventArgs {
      from_channel: None,
      to_channel: None, // required field
      recipient: None,
    }
  }
}

pub struct ChannelSwitchEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ChannelSwitchEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_from_channel(&mut self, from_channel: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChannelSwitchEvent::VT_FROM_CHANNEL, from_channel);
  }
  #[inline]
  pub fn add_to_channel(&mut self, to_channel: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChannelSwitchEvent::VT_TO_CHANNEL, to_channel);
  }
  #[inline]
  pub fn add_recipient(&mut self, recipient: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ChannelSwitchEvent::VT_RECIPIENT, recipient);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ChannelSwitchEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ChannelSwitchEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ChannelSwitchEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ChannelSwitchEvent::VT_TO_CHANNEL,"to_channel");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ChannelSwitchEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ChannelSwitchEvent");
      ds.field("from_channel", &self.from_channel());
      ds.field("to_channel", &self.to_channel());
      ds.field("recipient", &self.recipient());
      ds.finish()
  }
}
pub enum ContentDeltaEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ContentDeltaEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ContentDeltaEvent<'a> {
  type Inner = ContentDeltaEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ContentDeltaEvent<'a> {
  pub const VT_TEXT: flatbuffers::VOffsetT = 4;
  pub const VT_CHANNEL: flatbuffers::VOffsetT = 6;
  pub const VT_TOKEN_INDEX: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ContentDeltaEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ContentDeltaEventArgs<'args>
  ) -> flatbuffers::WIPOffset<ContentDeltaEvent<'bldr>> {
    let mut builder = ContentDeltaEventBuilder::new(_fbb);
    builder.add_token_index(args.token_index);
    if let Some(x) = args.channel { builder.add_channel(x); }
    if let Some(x) = args.text { builder.add_text(x); }
    builder.finish()
  }


  #[inline]
  pub fn text(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ContentDeltaEvent::VT_TEXT, None).unwrap()}
  }
  #[inline]
  pub fn channel(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ContentDeltaEvent::VT_CHANNEL, None)}
  }
  #[inline]
  pub fn token_index(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ContentDeltaEvent::VT_TOKEN_INDEX, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ContentDeltaEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("channel", Self::VT_CHANNEL, false)?
     .visit_field::<u32>("token_index", Self::VT_TOKEN_INDEX, false)?
     .finish();
    Ok(())
  }
}
pub struct ContentDeltaEventArgs<'a> {
    pub text: Option<flatbuffers::WIPOffset<&'a str>>,
    pub channel: Option<flatbuffers::WIPOffset<&'a str>>,
    pub token_index: u32,
}
impl<'a> Default for ContentDeltaEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    ContentDeltaEventArgs {
      text: None, // required field
      channel: None,
      token_index: 0,
    }
  }
}

pub struct ContentDeltaEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ContentDeltaEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_text(&mut self, text: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ContentDeltaEvent::VT_TEXT, text);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ContentDeltaEvent::VT_CHANNEL, channel);
  }
  #[inline]
  pub fn add_token_index(&mut self, token_index: u32) {
    self.fbb_.push_slot::<u32>(ContentDeltaEvent::VT_TOKEN_INDEX, token_index, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ContentDeltaEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ContentDeltaEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ContentDeltaEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ContentDeltaEvent::VT_TEXT,"text");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ContentDeltaEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ContentDeltaEvent");
      ds.field("text", &self.text());
      ds.field("channel", &self.channel());
      ds.field("token_index", &self.token_index());
      ds.finish()
  }
}
pub enum MessageCompleteEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct MessageCompleteEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for MessageCompleteEvent<'a> {
  type Inner = MessageCompleteEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> MessageCompleteEvent<'a> {
  pub const VT_ROLE: flatbuffers::VOffsetT = 4;
  pub const VT_CHANNEL: flatbuffers::VOffsetT = 6;
  pub const VT_TOTAL_CONTENT_LENGTH: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    MessageCompleteEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MessageCompleteEventArgs<'args>
  ) -> flatbuffers::WIPOffset<MessageCompleteEvent<'bldr>> {
    let mut builder = MessageCompleteEventBuilder::new(_fbb);
    builder.add_total_content_length(args.total_content_length);
    if let Some(x) = args.channel { builder.add_channel(x); }
    if let Some(x) = args.role { builder.add_role(x); }
    builder.finish()
  }


  #[inline]
  pub fn role(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MessageCompleteEvent::VT_ROLE, None).unwrap()}
  }
  #[inline]
  pub fn channel(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(MessageCompleteEvent::VT_CHANNEL, None)}
  }
  #[inline]
  pub fn total_content_length(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(MessageCompleteEvent::VT_TOTAL_CONTENT_LENGTH, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for MessageCompleteEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("role", Self::VT_ROLE, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("channel", Self::VT_CHANNEL, false)?
     .visit_field::<u32>("total_content_length", Self::VT_TOTAL_CONTENT_LENGTH, false)?
     .finish();
    Ok(())
  }
}
pub struct MessageCompleteEventArgs<'a> {
    pub role: Option<flatbuffers::WIPOffset<&'a str>>,
    pub channel: Option<flatbuffers::WIPOffset<&'a str>>,
    pub total_content_length: u32,
}
impl<'a> Default for MessageCompleteEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    MessageCompleteEventArgs {
      role: None, // required field
      channel: None,
      total_content_length: 0,
    }
  }
}

pub struct MessageCompleteEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MessageCompleteEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_role(&mut self, role: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MessageCompleteEvent::VT_ROLE, role);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(MessageCompleteEvent::VT_CHANNEL, channel);
  }
  #[inline]
  pub fn add_total_content_length(&mut self, total_content_length: u32) {
    self.fbb_.push_slot::<u32>(MessageCompleteEvent::VT_TOTAL_CONTENT_LENGTH, total_content_length, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> MessageCompleteEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MessageCompleteEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<MessageCompleteEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, MessageCompleteEvent::VT_ROLE,"role");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for MessageCompleteEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("MessageCompleteEvent");
      ds.field("role", &self.role());
      ds.field("channel", &self.channel());
      ds.field("total_content_length", &self.total_content_length());
      ds.finish()
  }
}
pub enum StreamCompleteEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct StreamCompleteEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for StreamCompleteEvent<'a> {
  type Inner = StreamCompleteEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> StreamCompleteEvent<'a> {
  pub const VT_REASON: flatbuffers::VOffsetT = 4;
  pub const VT_TOTAL_TOKENS: flatbuffers::VOffsetT = 6;
  pub const VT_GENERATION_TIME_MS: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    StreamCompleteEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StreamCompleteEventArgs<'args>
  ) -> flatbuffers::WIPOffset<StreamCompleteEvent<'bldr>> {
    let mut builder = StreamCompleteEventBuilder::new(_fbb);
    builder.add_generation_time_ms(args.generation_time_ms);
    builder.add_total_tokens(args.total_tokens);
    if let Some(x) = args.reason { builder.add_reason(x); }
    builder.finish()
  }


  #[inline]
  pub fn reason(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(StreamCompleteEvent::VT_REASON, None).unwrap()}
  }
  #[inline]
  pub fn total_tokens(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(StreamCompleteEvent::VT_TOTAL_TOKENS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn generation_time_ms(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(StreamCompleteEvent::VT_GENERATION_TIME_MS, Some(0)).unwrap()}
  }
}

impl flatbuffers::Verifiable for StreamCompleteEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("reason", Self::VT_REASON, true)?
     .visit_field::<u32>("total_tokens", Self::VT_TOTAL_TOKENS, false)?
     .visit_field::<u32>("generation_time_ms", Self::VT_GENERATION_TIME_MS, false)?
     .finish();
    Ok(())
  }
}
pub struct StreamCompleteEventArgs<'a> {
    pub reason: Option<flatbuffers::WIPOffset<&'a str>>,
    pub total_tokens: u32,
    pub generation_time_ms: u32,
}
impl<'a> Default for StreamCompleteEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    StreamCompleteEventArgs {
      reason: None, // required field
      total_tokens: 0,
      generation_time_ms: 0,
    }
  }
}

pub struct StreamCompleteEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> StreamCompleteEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_reason(&mut self, reason: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(StreamCompleteEvent::VT_REASON, reason);
  }
  #[inline]
  pub fn add_total_tokens(&mut self, total_tokens: u32) {
    self.fbb_.push_slot::<u32>(StreamCompleteEvent::VT_TOTAL_TOKENS, total_tokens, 0);
  }
  #[inline]
  pub fn add_generation_time_ms(&mut self, generation_time_ms: u32) {
    self.fbb_.push_slot::<u32>(StreamCompleteEvent::VT_GENERATION_TIME_MS, generation_time_ms, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> StreamCompleteEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StreamCompleteEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<StreamCompleteEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, StreamCompleteEvent::VT_REASON,"reason");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for StreamCompleteEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("StreamCompleteEvent");
      ds.field("reason", &self.reason());
      ds.field("total_tokens", &self.total_tokens());
      ds.field("generation_time_ms", &self.generation_time_ms());
      ds.finish()
  }
}
pub enum ParseErrorEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ParseErrorEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for ParseErrorEvent<'a> {
  type Inner = ParseErrorEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> ParseErrorEvent<'a> {
  pub const VT_ERROR_MESSAGE: flatbuffers::VOffsetT = 4;
  pub const VT_TOKEN_POSITION: flatbuffers::VOffsetT = 6;
  pub const VT_RECOVERY_ATTEMPTED: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    ParseErrorEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ParseErrorEventArgs<'args>
  ) -> flatbuffers::WIPOffset<ParseErrorEvent<'bldr>> {
    let mut builder = ParseErrorEventBuilder::new(_fbb);
    builder.add_token_position(args.token_position);
    if let Some(x) = args.error_message { builder.add_error_message(x); }
    builder.add_recovery_attempted(args.recovery_attempted);
    builder.finish()
  }


  #[inline]
  pub fn error_message(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(ParseErrorEvent::VT_ERROR_MESSAGE, None).unwrap()}
  }
  #[inline]
  pub fn token_position(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ParseErrorEvent::VT_TOKEN_POSITION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn recovery_attempted(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ParseErrorEvent::VT_RECOVERY_ATTEMPTED, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for ParseErrorEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("error_message", Self::VT_ERROR_MESSAGE, true)?
     .visit_field::<u32>("token_position", Self::VT_TOKEN_POSITION, false)?
     .visit_field::<bool>("recovery_attempted", Self::VT_RECOVERY_ATTEMPTED, false)?
     .finish();
    Ok(())
  }
}
pub struct ParseErrorEventArgs<'a> {
    pub error_message: Option<flatbuffers::WIPOffset<&'a str>>,
    pub token_position: u32,
    pub recovery_attempted: bool,
}
impl<'a> Default for ParseErrorEventArgs<'a> {
  #[inline]
  fn default() -> Self {
    ParseErrorEventArgs {
      error_message: None, // required field
      token_position: 0,
      recovery_attempted: false,
    }
  }
}

pub struct ParseErrorEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> ParseErrorEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_error_message(&mut self, error_message: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(ParseErrorEvent::VT_ERROR_MESSAGE, error_message);
  }
  #[inline]
  pub fn add_token_position(&mut self, token_position: u32) {
    self.fbb_.push_slot::<u32>(ParseErrorEvent::VT_TOKEN_POSITION, token_position, 0);
  }
  #[inline]
  pub fn add_recovery_attempted(&mut self, recovery_attempted: bool) {
    self.fbb_.push_slot::<bool>(ParseErrorEvent::VT_RECOVERY_ATTEMPTED, recovery_attempted, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> ParseErrorEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ParseErrorEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<ParseErrorEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, ParseErrorEvent::VT_ERROR_MESSAGE,"error_message");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for ParseErrorEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("ParseErrorEvent");
      ds.field("error_message", &self.error_message());
      ds.field("token_position", &self.token_position());
      ds.field("recovery_attempted", &self.recovery_attempted());
      ds.finish()
  }
}
pub enum NoesisEventOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct NoesisEvent<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for NoesisEvent<'a> {
  type Inner = NoesisEvent<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> NoesisEvent<'a> {
  pub const VT_TYPE_: flatbuffers::VOffsetT = 4;
  pub const VT_DATA_TYPE: flatbuffers::VOffsetT = 6;
  pub const VT_DATA: flatbuffers::VOffsetT = 8;
  pub const VT_TIMESTAMP_NS: flatbuffers::VOffsetT = 10;
  pub const VT_SEQUENCE_ID: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    NoesisEvent { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args NoesisEventArgs
  ) -> flatbuffers::WIPOffset<NoesisEvent<'bldr>> {
    let mut builder = NoesisEventBuilder::new(_fbb);
    builder.add_timestamp_ns(args.timestamp_ns);
    builder.add_sequence_id(args.sequence_id);
    if let Some(x) = args.data { builder.add_data(x); }
    builder.add_data_type(args.data_type);
    builder.add_type_(args.type_);
    builder.finish()
  }


  #[inline]
  pub fn type_(&self) -> EventType {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<EventType>(NoesisEvent::VT_TYPE_, Some(EventType::ToolCall)).unwrap()}
  }
  #[inline]
  pub fn data_type(&self) -> EventData {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<EventData>(NoesisEvent::VT_DATA_TYPE, Some(EventData::NONE)).unwrap()}
  }
  #[inline]
  pub fn data(&self) -> flatbuffers::Table<'a> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Table<'a>>>(NoesisEvent::VT_DATA, None).unwrap()}
  }
  #[inline]
  pub fn timestamp_ns(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(NoesisEvent::VT_TIMESTAMP_NS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sequence_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(NoesisEvent::VT_SEQUENCE_ID, Some(0)).unwrap()}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_tool_call_event(&self) -> Option<ToolCallEvent<'a>> {
    if self.data_type() == EventData::ToolCallEvent {
      let u = self.data();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { ToolCallEvent::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_channel_switch_event(&self) -> Option<ChannelSwitchEvent<'a>> {
    if self.data_type() == EventData::ChannelSwitchEvent {
      let u = self.data();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { ChannelSwitchEvent::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_content_delta_event(&self) -> Option<ContentDeltaEvent<'a>> {
    if self.data_type() == EventData::ContentDeltaEvent {
      let u = self.data();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { ContentDeltaEvent::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_message_complete_event(&self) -> Option<MessageCompleteEvent<'a>> {
    if self.data_type() == EventData::MessageCompleteEvent {
      let u = self.data();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { MessageCompleteEvent::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_stream_complete_event(&self) -> Option<StreamCompleteEvent<'a>> {
    if self.data_type() == EventData::StreamCompleteEvent {
      let u = self.data();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { StreamCompleteEvent::init_from_table(u) })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn data_as_parse_error_event(&self) -> Option<ParseErrorEvent<'a>> {
    if self.data_type() == EventData::ParseErrorEvent {
      let u = self.data();
      // Safety:
      // Created from a valid Table for this object
      // Which contains a valid union in this slot
      Some(unsafe { ParseErrorEvent::init_from_table(u) })
    } else {
      None
    }
  }

}

impl flatbuffers::Verifiable for NoesisEvent<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<EventType>("type_", Self::VT_TYPE_, false)?
     .visit_union::<EventData, _>("data_type", Self::VT_DATA_TYPE, "data", Self::VT_DATA, true, |key, v, pos| {
        match key {
          EventData::ToolCallEvent => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ToolCallEvent>>("EventData::ToolCallEvent", pos),
          EventData::ChannelSwitchEvent => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ChannelSwitchEvent>>("EventData::ChannelSwitchEvent", pos),
          EventData::ContentDeltaEvent => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ContentDeltaEvent>>("EventData::ContentDeltaEvent", pos),
          EventData::MessageCompleteEvent => v.verify_union_variant::<flatbuffers::ForwardsUOffset<MessageCompleteEvent>>("EventData::MessageCompleteEvent", pos),
          EventData::StreamCompleteEvent => v.verify_union_variant::<flatbuffers::ForwardsUOffset<StreamCompleteEvent>>("EventData::StreamCompleteEvent", pos),
          EventData::ParseErrorEvent => v.verify_union_variant::<flatbuffers::ForwardsUOffset<ParseErrorEvent>>("EventData::ParseErrorEvent", pos),
          _ => Ok(()),
        }
     })?
     .visit_field::<u64>("timestamp_ns", Self::VT_TIMESTAMP_NS, false)?
     .visit_field::<u32>("sequence_id", Self::VT_SEQUENCE_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct NoesisEventArgs {
    pub type_: EventType,
    pub data_type: EventData,
    pub data: Option<flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>>,
    pub timestamp_ns: u64,
    pub sequence_id: u32,
}
impl<'a> Default for NoesisEventArgs {
  #[inline]
  fn default() -> Self {
    NoesisEventArgs {
      type_: EventType::ToolCall,
      data_type: EventData::NONE,
      data: None, // required field
      timestamp_ns: 0,
      sequence_id: 0,
    }
  }
}

pub struct NoesisEventBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> NoesisEventBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_type_(&mut self, type_: EventType) {
    self.fbb_.push_slot::<EventType>(NoesisEvent::VT_TYPE_, type_, EventType::ToolCall);
  }
  #[inline]
  pub fn add_data_type(&mut self, data_type: EventData) {
    self.fbb_.push_slot::<EventData>(NoesisEvent::VT_DATA_TYPE, data_type, EventData::NONE);
  }
  #[inline]
  pub fn add_data(&mut self, data: flatbuffers::WIPOffset<flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(NoesisEvent::VT_DATA, data);
  }
  #[inline]
  pub fn add_timestamp_ns(&mut self, timestamp_ns: u64) {
    self.fbb_.push_slot::<u64>(NoesisEvent::VT_TIMESTAMP_NS, timestamp_ns, 0);
  }
  #[inline]
  pub fn add_sequence_id(&mut self, sequence_id: u32) {
    self.fbb_.push_slot::<u32>(NoesisEvent::VT_SEQUENCE_ID, sequence_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> NoesisEventBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    NoesisEventBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<NoesisEvent<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, NoesisEvent::VT_DATA,"data");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for NoesisEvent<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("NoesisEvent");
      ds.field("type_", &self.type_());
      ds.field("data_type", &self.data_type());
      match self.data_type() {
        EventData::ToolCallEvent => {
          if let Some(x) = self.data_as_tool_call_event() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EventData::ChannelSwitchEvent => {
          if let Some(x) = self.data_as_channel_switch_event() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EventData::ContentDeltaEvent => {
          if let Some(x) = self.data_as_content_delta_event() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EventData::MessageCompleteEvent => {
          if let Some(x) = self.data_as_message_complete_event() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EventData::StreamCompleteEvent => {
          if let Some(x) = self.data_as_stream_complete_event() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        EventData::ParseErrorEvent => {
          if let Some(x) = self.data_as_parse_error_event() {
            ds.field("data", &x)
          } else {
            ds.field("data", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("data", &x)
        },
      };
      ds.field("timestamp_ns", &self.timestamp_ns());
      ds.field("sequence_id", &self.sequence_id());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `NoesisEvent`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_noesis_event_unchecked`.
pub fn root_as_noesis_event(buf: &[u8]) -> Result<NoesisEvent, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<NoesisEvent>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `NoesisEvent` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_noesis_event_unchecked`.
pub fn size_prefixed_root_as_noesis_event(buf: &[u8]) -> Result<NoesisEvent, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<NoesisEvent>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `NoesisEvent` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_noesis_event_unchecked`.
pub fn root_as_noesis_event_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NoesisEvent<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<NoesisEvent<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `NoesisEvent` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_noesis_event_unchecked`.
pub fn size_prefixed_root_as_noesis_event_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<NoesisEvent<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<NoesisEvent<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a NoesisEvent and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `NoesisEvent`.
pub unsafe fn root_as_noesis_event_unchecked(buf: &[u8]) -> NoesisEvent {
  flatbuffers::root_unchecked::<NoesisEvent>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed NoesisEvent and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `NoesisEvent`.
pub unsafe fn size_prefixed_root_as_noesis_event_unchecked(buf: &[u8]) -> NoesisEvent {
  flatbuffers::size_prefixed_root_unchecked::<NoesisEvent>(buf)
}
#[inline]
pub fn finish_noesis_event_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<NoesisEvent<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_noesis_event_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<NoesisEvent<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod events
}  // pub mod noesis
}  // pub mod koog
}  // pub mod ai

