// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod ai {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod koog {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod noesis {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};
#[allow(unused_imports, dead_code)]
pub mod protocol {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_ROLE: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_ROLE: i8 = 4;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_ROLE: [Role; 5] = [
  Role::User,
  Role::Assistant,
  Role::System,
  Role::Developer,
  Role::Tool,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Role(pub i8);
#[allow(non_upper_case_globals)]
impl Role {
  pub const User: Self = Self(0);
  pub const Assistant: Self = Self(1);
  pub const System: Self = Self(2);
  pub const Developer: Self = Self(3);
  pub const Tool: Self = Self(4);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 4;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::User,
    Self::Assistant,
    Self::System,
    Self::Developer,
    Self::Tool,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::User => Some("User"),
      Self::Assistant => Some("Assistant"),
      Self::System => Some("System"),
      Self::Developer => Some("Developer"),
      Self::Tool => Some("Tool"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for Role {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for Role {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for Role {
    type Output = Role;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<i8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for Role {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for Role {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for Role {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_REASONING_EFFORT: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_REASONING_EFFORT: i8 = 2;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_REASONING_EFFORT: [ReasoningEffort; 3] = [
  ReasoningEffort::Low,
  ReasoningEffort::Medium,
  ReasoningEffort::High,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct ReasoningEffort(pub i8);
#[allow(non_upper_case_globals)]
impl ReasoningEffort {
  pub const Low: Self = Self(0);
  pub const Medium: Self = Self(1);
  pub const High: Self = Self(2);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 2;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Low,
    Self::Medium,
    Self::High,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Low => Some("Low"),
      Self::Medium => Some("Medium"),
      Self::High => Some("High"),
      _ => None,
    }
  }
}
impl core::fmt::Debug for ReasoningEffort {
  fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> flatbuffers::Follow<'a> for ReasoningEffort {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl flatbuffers::Push for ReasoningEffort {
    type Output = ReasoningEffort;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { flatbuffers::emplace_scalar::<i8>(dst, self.0); }
    }
}

impl flatbuffers::EndianScalar for ReasoningEffort {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> flatbuffers::Verifiable for ReasoningEffort {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    i8::run_verifier(v, pos)
  }
}

impl flatbuffers::SimpleToVerifyInSlice for ReasoningEffort {}
pub enum MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Message<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Message<'a> {
  type Inner = Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Message<'a> {
  pub const VT_ROLE: flatbuffers::VOffsetT = 4;
  pub const VT_CONTENT: flatbuffers::VOffsetT = 6;
  pub const VT_CHANNEL: flatbuffers::VOffsetT = 8;
  pub const VT_RECIPIENT: flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MessageArgs<'args>
  ) -> flatbuffers::WIPOffset<Message<'bldr>> {
    let mut builder = MessageBuilder::new(_fbb);
    if let Some(x) = args.recipient { builder.add_recipient(x); }
    if let Some(x) = args.channel { builder.add_channel(x); }
    if let Some(x) = args.content { builder.add_content(x); }
    builder.add_role(args.role);
    builder.finish()
  }


  #[inline]
  pub fn role(&self) -> Role {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<Role>(Message::VT_ROLE, Some(Role::User)).unwrap()}
  }
  #[inline]
  pub fn content(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Message::VT_CONTENT, None).unwrap()}
  }
  #[inline]
  pub fn channel(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Message::VT_CHANNEL, None)}
  }
  #[inline]
  pub fn recipient(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Message::VT_RECIPIENT, None)}
  }
}

impl flatbuffers::Verifiable for Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<Role>("role", Self::VT_ROLE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("content", Self::VT_CONTENT, true)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("channel", Self::VT_CHANNEL, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("recipient", Self::VT_RECIPIENT, false)?
     .finish();
    Ok(())
  }
}
pub struct MessageArgs<'a> {
    pub role: Role,
    pub content: Option<flatbuffers::WIPOffset<&'a str>>,
    pub channel: Option<flatbuffers::WIPOffset<&'a str>>,
    pub recipient: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for MessageArgs<'a> {
  #[inline]
  fn default() -> Self {
    MessageArgs {
      role: Role::User,
      content: None, // required field
      channel: None,
      recipient: None,
    }
  }
}

pub struct MessageBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> MessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_role(&mut self, role: Role) {
    self.fbb_.push_slot::<Role>(Message::VT_ROLE, role, Role::User);
  }
  #[inline]
  pub fn add_content(&mut self, content: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Message::VT_CONTENT, content);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Message::VT_CHANNEL, channel);
  }
  #[inline]
  pub fn add_recipient(&mut self, recipient: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Message::VT_RECIPIENT, recipient);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> MessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, Message::VT_CONTENT,"content");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Message<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Message");
      ds.field("role", &self.role());
      ds.field("content", &self.content());
      ds.field("channel", &self.channel());
      ds.field("recipient", &self.recipient());
      ds.finish()
  }
}
pub enum SystemConfigOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SystemConfig<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for SystemConfig<'a> {
  type Inner = SystemConfig<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SystemConfig<'a> {
  pub const VT_MODEL_IDENTITY: flatbuffers::VOffsetT = 4;
  pub const VT_REASONING_EFFORT: flatbuffers::VOffsetT = 6;
  pub const VT_KNOWLEDGE_CUTOFF: flatbuffers::VOffsetT = 8;
  pub const VT_CONVERSATION_START_DATE: flatbuffers::VOffsetT = 10;
  pub const VT_REQUIRED_CHANNELS: flatbuffers::VOffsetT = 12;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    SystemConfig { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SystemConfigArgs<'args>
  ) -> flatbuffers::WIPOffset<SystemConfig<'bldr>> {
    let mut builder = SystemConfigBuilder::new(_fbb);
    if let Some(x) = args.required_channels { builder.add_required_channels(x); }
    if let Some(x) = args.conversation_start_date { builder.add_conversation_start_date(x); }
    if let Some(x) = args.knowledge_cutoff { builder.add_knowledge_cutoff(x); }
    if let Some(x) = args.model_identity { builder.add_model_identity(x); }
    builder.add_reasoning_effort(args.reasoning_effort);
    builder.finish()
  }


  #[inline]
  pub fn model_identity(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SystemConfig::VT_MODEL_IDENTITY, None)}
  }
  #[inline]
  pub fn reasoning_effort(&self) -> ReasoningEffort {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<ReasoningEffort>(SystemConfig::VT_REASONING_EFFORT, Some(ReasoningEffort::Medium)).unwrap()}
  }
  #[inline]
  pub fn knowledge_cutoff(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SystemConfig::VT_KNOWLEDGE_CUTOFF, None)}
  }
  #[inline]
  pub fn conversation_start_date(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(SystemConfig::VT_CONVERSATION_START_DATE, None)}
  }
  #[inline]
  pub fn required_channels(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(SystemConfig::VT_REQUIRED_CHANNELS, None)}
  }
}

impl flatbuffers::Verifiable for SystemConfig<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("model_identity", Self::VT_MODEL_IDENTITY, false)?
     .visit_field::<ReasoningEffort>("reasoning_effort", Self::VT_REASONING_EFFORT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("knowledge_cutoff", Self::VT_KNOWLEDGE_CUTOFF, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("conversation_start_date", Self::VT_CONVERSATION_START_DATE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("required_channels", Self::VT_REQUIRED_CHANNELS, false)?
     .finish();
    Ok(())
  }
}
pub struct SystemConfigArgs<'a> {
    pub model_identity: Option<flatbuffers::WIPOffset<&'a str>>,
    pub reasoning_effort: ReasoningEffort,
    pub knowledge_cutoff: Option<flatbuffers::WIPOffset<&'a str>>,
    pub conversation_start_date: Option<flatbuffers::WIPOffset<&'a str>>,
    pub required_channels: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
}
impl<'a> Default for SystemConfigArgs<'a> {
  #[inline]
  fn default() -> Self {
    SystemConfigArgs {
      model_identity: None,
      reasoning_effort: ReasoningEffort::Medium,
      knowledge_cutoff: None,
      conversation_start_date: None,
      required_channels: None,
    }
  }
}

pub struct SystemConfigBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> SystemConfigBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_model_identity(&mut self, model_identity: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemConfig::VT_MODEL_IDENTITY, model_identity);
  }
  #[inline]
  pub fn add_reasoning_effort(&mut self, reasoning_effort: ReasoningEffort) {
    self.fbb_.push_slot::<ReasoningEffort>(SystemConfig::VT_REASONING_EFFORT, reasoning_effort, ReasoningEffort::Medium);
  }
  #[inline]
  pub fn add_knowledge_cutoff(&mut self, knowledge_cutoff: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemConfig::VT_KNOWLEDGE_CUTOFF, knowledge_cutoff);
  }
  #[inline]
  pub fn add_conversation_start_date(&mut self, conversation_start_date: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemConfig::VT_CONVERSATION_START_DATE, conversation_start_date);
  }
  #[inline]
  pub fn add_required_channels(&mut self, required_channels: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(SystemConfig::VT_REQUIRED_CHANNELS, required_channels);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> SystemConfigBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SystemConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<SystemConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for SystemConfig<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("SystemConfig");
      ds.field("model_identity", &self.model_identity());
      ds.field("reasoning_effort", &self.reasoning_effort());
      ds.field("knowledge_cutoff", &self.knowledge_cutoff());
      ds.field("conversation_start_date", &self.conversation_start_date());
      ds.field("required_channels", &self.required_channels());
      ds.finish()
  }
}
pub enum DeveloperConfigOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DeveloperConfig<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DeveloperConfig<'a> {
  type Inner = DeveloperConfig<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DeveloperConfig<'a> {
  pub const VT_INSTRUCTIONS: flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    DeveloperConfig { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DeveloperConfigArgs<'args>
  ) -> flatbuffers::WIPOffset<DeveloperConfig<'bldr>> {
    let mut builder = DeveloperConfigBuilder::new(_fbb);
    if let Some(x) = args.instructions { builder.add_instructions(x); }
    builder.finish()
  }


  #[inline]
  pub fn instructions(&self) -> &'a str {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(DeveloperConfig::VT_INSTRUCTIONS, None).unwrap()}
  }
}

impl flatbuffers::Verifiable for DeveloperConfig<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("instructions", Self::VT_INSTRUCTIONS, true)?
     .finish();
    Ok(())
  }
}
pub struct DeveloperConfigArgs<'a> {
    pub instructions: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for DeveloperConfigArgs<'a> {
  #[inline]
  fn default() -> Self {
    DeveloperConfigArgs {
      instructions: None, // required field
    }
  }
}

pub struct DeveloperConfigBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> DeveloperConfigBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_instructions(&mut self, instructions: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(DeveloperConfig::VT_INSTRUCTIONS, instructions);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> DeveloperConfigBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DeveloperConfigBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<DeveloperConfig<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, DeveloperConfig::VT_INSTRUCTIONS,"instructions");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for DeveloperConfig<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("DeveloperConfig");
      ds.field("instructions", &self.instructions());
      ds.finish()
  }
}
pub enum GenerationRequestOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GenerationRequest<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GenerationRequest<'a> {
  type Inner = GenerationRequest<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GenerationRequest<'a> {
  pub const VT_MODEL_HANDLE: flatbuffers::VOffsetT = 4;
  pub const VT_SYSTEM_CONFIG: flatbuffers::VOffsetT = 6;
  pub const VT_DEVELOPER_CONFIG: flatbuffers::VOffsetT = 8;
  pub const VT_MESSAGES: flatbuffers::VOffsetT = 10;
  pub const VT_MAX_TOKENS: flatbuffers::VOffsetT = 12;
  pub const VT_TEMPERATURE: flatbuffers::VOffsetT = 14;
  pub const VT_TOP_P: flatbuffers::VOffsetT = 16;
  pub const VT_TOP_K: flatbuffers::VOffsetT = 18;
  pub const VT_SEED: flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GenerationRequest { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GenerationRequestArgs<'args>
  ) -> flatbuffers::WIPOffset<GenerationRequest<'bldr>> {
    let mut builder = GenerationRequestBuilder::new(_fbb);
    builder.add_model_handle(args.model_handle);
    builder.add_seed(args.seed);
    builder.add_top_k(args.top_k);
    builder.add_top_p(args.top_p);
    builder.add_temperature(args.temperature);
    builder.add_max_tokens(args.max_tokens);
    if let Some(x) = args.messages { builder.add_messages(x); }
    if let Some(x) = args.developer_config { builder.add_developer_config(x); }
    if let Some(x) = args.system_config { builder.add_system_config(x); }
    builder.finish()
  }


  #[inline]
  pub fn model_handle(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(GenerationRequest::VT_MODEL_HANDLE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn system_config(&self) -> Option<SystemConfig<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<SystemConfig>>(GenerationRequest::VT_SYSTEM_CONFIG, None)}
  }
  #[inline]
  pub fn developer_config(&self) -> Option<DeveloperConfig<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<DeveloperConfig>>(GenerationRequest::VT_DEVELOPER_CONFIG, None)}
  }
  #[inline]
  pub fn messages(&self) -> flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Message<'a>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Message>>>>(GenerationRequest::VT_MESSAGES, None).unwrap()}
  }
  #[inline]
  pub fn max_tokens(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(GenerationRequest::VT_MAX_TOKENS, Some(2048)).unwrap()}
  }
  #[inline]
  pub fn temperature(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(GenerationRequest::VT_TEMPERATURE, Some(0.7)).unwrap()}
  }
  #[inline]
  pub fn top_p(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(GenerationRequest::VT_TOP_P, Some(0.9)).unwrap()}
  }
  #[inline]
  pub fn top_k(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(GenerationRequest::VT_TOP_K, Some(40)).unwrap()}
  }
  #[inline]
  pub fn seed(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(GenerationRequest::VT_SEED, Some(42)).unwrap()}
  }
}

impl flatbuffers::Verifiable for GenerationRequest<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i64>("model_handle", Self::VT_MODEL_HANDLE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<SystemConfig>>("system_config", Self::VT_SYSTEM_CONFIG, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<DeveloperConfig>>("developer_config", Self::VT_DEVELOPER_CONFIG, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<Message>>>>("messages", Self::VT_MESSAGES, true)?
     .visit_field::<i32>("max_tokens", Self::VT_MAX_TOKENS, false)?
     .visit_field::<f32>("temperature", Self::VT_TEMPERATURE, false)?
     .visit_field::<f32>("top_p", Self::VT_TOP_P, false)?
     .visit_field::<i32>("top_k", Self::VT_TOP_K, false)?
     .visit_field::<u32>("seed", Self::VT_SEED, false)?
     .finish();
    Ok(())
  }
}
pub struct GenerationRequestArgs<'a> {
    pub model_handle: i64,
    pub system_config: Option<flatbuffers::WIPOffset<SystemConfig<'a>>>,
    pub developer_config: Option<flatbuffers::WIPOffset<DeveloperConfig<'a>>>,
    pub messages: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<Message<'a>>>>>,
    pub max_tokens: i32,
    pub temperature: f32,
    pub top_p: f32,
    pub top_k: i32,
    pub seed: u32,
}
impl<'a> Default for GenerationRequestArgs<'a> {
  #[inline]
  fn default() -> Self {
    GenerationRequestArgs {
      model_handle: 0,
      system_config: None,
      developer_config: None,
      messages: None, // required field
      max_tokens: 2048,
      temperature: 0.7,
      top_p: 0.9,
      top_k: 40,
      seed: 42,
    }
  }
}

pub struct GenerationRequestBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GenerationRequestBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_model_handle(&mut self, model_handle: i64) {
    self.fbb_.push_slot::<i64>(GenerationRequest::VT_MODEL_HANDLE, model_handle, 0);
  }
  #[inline]
  pub fn add_system_config(&mut self, system_config: flatbuffers::WIPOffset<SystemConfig<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<SystemConfig>>(GenerationRequest::VT_SYSTEM_CONFIG, system_config);
  }
  #[inline]
  pub fn add_developer_config(&mut self, developer_config: flatbuffers::WIPOffset<DeveloperConfig<'b >>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<DeveloperConfig>>(GenerationRequest::VT_DEVELOPER_CONFIG, developer_config);
  }
  #[inline]
  pub fn add_messages(&mut self, messages: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<Message<'b >>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GenerationRequest::VT_MESSAGES, messages);
  }
  #[inline]
  pub fn add_max_tokens(&mut self, max_tokens: i32) {
    self.fbb_.push_slot::<i32>(GenerationRequest::VT_MAX_TOKENS, max_tokens, 2048);
  }
  #[inline]
  pub fn add_temperature(&mut self, temperature: f32) {
    self.fbb_.push_slot::<f32>(GenerationRequest::VT_TEMPERATURE, temperature, 0.7);
  }
  #[inline]
  pub fn add_top_p(&mut self, top_p: f32) {
    self.fbb_.push_slot::<f32>(GenerationRequest::VT_TOP_P, top_p, 0.9);
  }
  #[inline]
  pub fn add_top_k(&mut self, top_k: i32) {
    self.fbb_.push_slot::<i32>(GenerationRequest::VT_TOP_K, top_k, 40);
  }
  #[inline]
  pub fn add_seed(&mut self, seed: u32) {
    self.fbb_.push_slot::<u32>(GenerationRequest::VT_SEED, seed, 42);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GenerationRequestBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GenerationRequestBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GenerationRequest<'a>> {
    let o = self.fbb_.end_table(self.start_);
    self.fbb_.required(o, GenerationRequest::VT_MESSAGES,"messages");
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GenerationRequest<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GenerationRequest");
      ds.field("model_handle", &self.model_handle());
      ds.field("system_config", &self.system_config());
      ds.field("developer_config", &self.developer_config());
      ds.field("messages", &self.messages());
      ds.field("max_tokens", &self.max_tokens());
      ds.field("temperature", &self.temperature());
      ds.field("top_p", &self.top_p());
      ds.field("top_k", &self.top_k());
      ds.field("seed", &self.seed());
      ds.finish()
  }
}
pub enum TokenChunkOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct TokenChunk<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TokenChunk<'a> {
  type Inner = TokenChunk<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> TokenChunk<'a> {
  pub const VT_TOKENS: flatbuffers::VOffsetT = 4;
  pub const VT_CHANNEL: flatbuffers::VOffsetT = 6;
  pub const VT_IS_FINAL: flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    TokenChunk { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args TokenChunkArgs<'args>
  ) -> flatbuffers::WIPOffset<TokenChunk<'bldr>> {
    let mut builder = TokenChunkBuilder::new(_fbb);
    if let Some(x) = args.channel { builder.add_channel(x); }
    if let Some(x) = args.tokens { builder.add_tokens(x); }
    builder.add_is_final(args.is_final);
    builder.finish()
  }


  #[inline]
  pub fn tokens(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(TokenChunk::VT_TOKENS, None)}
  }
  #[inline]
  pub fn channel(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(TokenChunk::VT_CHANNEL, None)}
  }
  #[inline]
  pub fn is_final(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(TokenChunk::VT_IS_FINAL, Some(false)).unwrap()}
  }
}

impl flatbuffers::Verifiable for TokenChunk<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("tokens", Self::VT_TOKENS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("channel", Self::VT_CHANNEL, false)?
     .visit_field::<bool>("is_final", Self::VT_IS_FINAL, false)?
     .finish();
    Ok(())
  }
}
pub struct TokenChunkArgs<'a> {
    pub tokens: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub channel: Option<flatbuffers::WIPOffset<&'a str>>,
    pub is_final: bool,
}
impl<'a> Default for TokenChunkArgs<'a> {
  #[inline]
  fn default() -> Self {
    TokenChunkArgs {
      tokens: None,
      channel: None,
      is_final: false,
    }
  }
}

pub struct TokenChunkBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> TokenChunkBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_tokens(&mut self, tokens: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TokenChunk::VT_TOKENS, tokens);
  }
  #[inline]
  pub fn add_channel(&mut self, channel: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(TokenChunk::VT_CHANNEL, channel);
  }
  #[inline]
  pub fn add_is_final(&mut self, is_final: bool) {
    self.fbb_.push_slot::<bool>(TokenChunk::VT_IS_FINAL, is_final, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> TokenChunkBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    TokenChunkBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<TokenChunk<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for TokenChunk<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("TokenChunk");
      ds.field("tokens", &self.tokens());
      ds.field("channel", &self.channel());
      ds.field("is_final", &self.is_final());
      ds.finish()
  }
}
pub enum GenerationResponseOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GenerationResponse<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for GenerationResponse<'a> {
  type Inner = GenerationResponse<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GenerationResponse<'a> {
  pub const VT_REQUEST_ID: flatbuffers::VOffsetT = 4;
  pub const VT_TOKENS: flatbuffers::VOffsetT = 6;
  pub const VT_TEXT: flatbuffers::VOffsetT = 8;
  pub const VT_CHANNELS: flatbuffers::VOffsetT = 10;
  pub const VT_METADATA: flatbuffers::VOffsetT = 12;
  pub const VT_ERROR: flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    GenerationResponse { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args GenerationResponseArgs<'args>
  ) -> flatbuffers::WIPOffset<GenerationResponse<'bldr>> {
    let mut builder = GenerationResponseBuilder::new(_fbb);
    if let Some(x) = args.error { builder.add_error(x); }
    if let Some(x) = args.metadata { builder.add_metadata(x); }
    if let Some(x) = args.channels { builder.add_channels(x); }
    if let Some(x) = args.text { builder.add_text(x); }
    if let Some(x) = args.tokens { builder.add_tokens(x); }
    if let Some(x) = args.request_id { builder.add_request_id(x); }
    builder.finish()
  }


  #[inline]
  pub fn request_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GenerationResponse::VT_REQUEST_ID, None)}
  }
  #[inline]
  pub fn tokens(&self) -> Option<flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(GenerationResponse::VT_TOKENS, None)}
  }
  #[inline]
  pub fn text(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GenerationResponse::VT_TEXT, None)}
  }
  #[inline]
  pub fn channels(&self) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>(GenerationResponse::VT_CHANNELS, None)}
  }
  #[inline]
  pub fn metadata(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GenerationResponse::VT_METADATA, None)}
  }
  #[inline]
  pub fn error(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(GenerationResponse::VT_ERROR, None)}
  }
}

impl flatbuffers::Verifiable for GenerationResponse<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("request_id", Self::VT_REQUEST_ID, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>("tokens", Self::VT_TOKENS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("text", Self::VT_TEXT, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<&'_ str>>>>("channels", Self::VT_CHANNELS, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("metadata", Self::VT_METADATA, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("error", Self::VT_ERROR, false)?
     .finish();
    Ok(())
  }
}
pub struct GenerationResponseArgs<'a> {
    pub request_id: Option<flatbuffers::WIPOffset<&'a str>>,
    pub tokens: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub text: Option<flatbuffers::WIPOffset<&'a str>>,
    pub channels: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub metadata: Option<flatbuffers::WIPOffset<&'a str>>,
    pub error: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for GenerationResponseArgs<'a> {
  #[inline]
  fn default() -> Self {
    GenerationResponseArgs {
      request_id: None,
      tokens: None,
      text: None,
      channels: None,
      metadata: None,
      error: None,
    }
  }
}

pub struct GenerationResponseBuilder<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: flatbuffers::Allocator + 'a> GenerationResponseBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_request_id(&mut self, request_id: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GenerationResponse::VT_REQUEST_ID, request_id);
  }
  #[inline]
  pub fn add_tokens(&mut self, tokens: flatbuffers::WIPOffset<flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GenerationResponse::VT_TOKENS, tokens);
  }
  #[inline]
  pub fn add_text(&mut self, text: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GenerationResponse::VT_TEXT, text);
  }
  #[inline]
  pub fn add_channels(&mut self, channels: flatbuffers::WIPOffset<flatbuffers::Vector<'b , flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GenerationResponse::VT_CHANNELS, channels);
  }
  #[inline]
  pub fn add_metadata(&mut self, metadata: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GenerationResponse::VT_METADATA, metadata);
  }
  #[inline]
  pub fn add_error(&mut self, error: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(GenerationResponse::VT_ERROR, error);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>) -> GenerationResponseBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GenerationResponseBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<GenerationResponse<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for GenerationResponse<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("GenerationResponse");
      ds.field("request_id", &self.request_id());
      ds.field("tokens", &self.tokens());
      ds.field("text", &self.text());
      ds.field("channels", &self.channels());
      ds.field("metadata", &self.metadata());
      ds.field("error", &self.error());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `GenerationRequest`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_generation_request_unchecked`.
pub fn root_as_generation_request(buf: &[u8]) -> Result<GenerationRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<GenerationRequest>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `GenerationRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_generation_request_unchecked`.
pub fn size_prefixed_root_as_generation_request(buf: &[u8]) -> Result<GenerationRequest, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<GenerationRequest>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `GenerationRequest` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_generation_request_unchecked`.
pub fn root_as_generation_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GenerationRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<GenerationRequest<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `GenerationRequest` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_generation_request_unchecked`.
pub fn size_prefixed_root_as_generation_request_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<GenerationRequest<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<GenerationRequest<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a GenerationRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `GenerationRequest`.
pub unsafe fn root_as_generation_request_unchecked(buf: &[u8]) -> GenerationRequest {
  unsafe { flatbuffers::root_unchecked::<GenerationRequest>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed GenerationRequest and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `GenerationRequest`.
pub unsafe fn size_prefixed_root_as_generation_request_unchecked(buf: &[u8]) -> GenerationRequest {
  unsafe { flatbuffers::size_prefixed_root_unchecked::<GenerationRequest>(buf) }
}
#[inline]
pub fn finish_generation_request_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>,
    root: flatbuffers::WIPOffset<GenerationRequest<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_generation_request_buffer<'a, 'b, A: flatbuffers::Allocator + 'a>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a, A>, root: flatbuffers::WIPOffset<GenerationRequest<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod protocol
}  // pub mod noesis
}  // pub mod koog
}  // pub mod ai

